### PR TITLE
Remove the deprecated numpy dtypes "int" and "float"

### PR DESCRIPTION
**Pull request by jaycedowell**

### CODE REVIEW

**Comment by jaycedowell** [comment]
It looks like this has sorta kinda already been merged in but with `numpy.int64` replacing `numpy.int` and `numpy.float64` replacing `numpy.float`.  I _think_ those are the correct sizes for native Python int's and float's so maybe this PR isn't needed?

**Comment by jaycedowell** [comment]
@dentalfloss1 @league  Any opinions on this PR which would allow lower precision values to be stored in a "standard header"?  I'm currently leaning towards keeping the current behavior in `master` and not merging this one.

**Comment by dentalfloss1** [comment]
I agree.

**Comment by jaycedowell** [comment]
Motion carries, closing.

**Pull request closed without merging**
