### PR TITLE
complex support for reduce

### PR DESCRIPTION
**Pull request by jaycedowell**
Support for reduce operations on complex types.  This also includes reduce operations on the absolute value of the input for both real and complex types.

### CODE REVIEW

**Comment by jaycedowell** [comment]
Docker is unhappy.

**Comment by jaycedowell** [comment]
Any action on this?

**Comment by jaycedowell** [comment]
Oh yeah, good call.  I had forgotten about the blocks.

**Comment by jaycedowell** [comment]
I don't think there is anything I can do about codecov checks failing because the reduce block runs on the GPU.

**Comment by telegraphic** [comment]
Well, FWIW I'm happy for this to be merged

**Comment by telegraphic** [comment]
to add -- the unittest for complex reduce passes when I ran it too

**Comment by jaycedowell** [comment]
Ok, cool.  @benbarsdell any other comments?

**Comment by jaycedowell** [comment]
No further comments after three weeks, merging.

**Pull request merged**
