### PR TITLE
GPU Unpack, take four

### PR DESCRIPTION
**Pull request by jaycedowell**
Add support for GPU-based unpacking and quantization (fourth attempt). This includes:
* GPU functions for unpacking integer data into 'i8'/'ci8'
* Functions to unpack integer data and promote to float/double
* Support for unpacking 1-bit data as:
  * 0 unpacks to -1
  * 1 unpacks to 1
* Preliminary support for packing into 'i2'/'ci2' and 'i1'/'ci1'. Full support held up by a check for padded arrays.

### CODE REVIEW

**Comment by jaycedowell** [comment]
This is like take three but puts the new GPU quantizer/unpacker into .cu and .hu files to preserve the history in `quantize.cpp` and `unpack.cpp`.  This also adds additional unit tests for the GPU functions and the promotion functions.

**Comment by MilesCranmer** [comment]
Looks good to me! @benbarsdell do you have any issues with this?

**Comment by benbarsdell** [comment]
I'm not sure what happened to the CI tests here; any ideas?. All tests pass when I run this branch locally.

**Comment by jaycedowell** [comment]
I'm not sure what is going on here.  I just triggered a build of master and ended up with the same error that kills this PR.  I think the culprit may be:

`test_block.py:315: UserWarning: loadtxt: Empty input file: ".log.txt"
  result = np.loadtxt(self.logfile).astype(np.float32).view(np.complex64)`

although I don't fully understand what this means.

**Comment by jaycedowell** [comment]
That's interesting.  I restarted a build from the jaycedowell-gpu-unpack2 branch that was previously marked as successful and it failed.

**Comment by jaycedowell** [comment]
Ah, it's the NumPy version.  I rolled back the NumPy version in the `.travis.yaml` file from the latest (1.14.3) to 1.13.3 using the jaycedowell-travistest branch and the build works.

**Comment by jaycedowell** [comment]
Making sure that files are closed after `np.savetxt()` is called with a file handle fixes the testing problem.

**Comment by benbarsdell** [comment]
Thanks for tracking that down Jayce!

**Pull request merged**
