### PR TITLE
Add cudaver to docs

### PR DESCRIPTION
**Pull request by dentalfloss1**
Adds a link to the docs where a table of test results of the CUDA toolkit live. The table has been added to the docs, but of course, we'll also need to update the hosted version of the docs.

### CODE REVIEW

**Comment by jaycedowell** [comment]
Two questions:
 * What does "likely working" mean?
 * The comments in #201 imply that CUDA 11.8 doesn't actually work but I also see this listed as likely working in the table.  Does the test suite pass?

**Comment by dentalfloss1** [comment]
Perhaps we can just change "likely working" to "working." The card I was using sometimes puts values just out of spec for the tests, so technically no tests would fully pass. It's weird and confusing. Let's just upgrade all "likely working" to "working." 
That bug is interesting. All the tests passed I believe on 11.8. But, if we have an existing issue with 11.8 perhaps we should just say "not working" to be safe. 
What do you think?

**Comment by jaycedowell** [comment]
Yes and yes.  I'll update the table.

**Comment by jaycedowell** [comment]
What do you think about dropping the "CUDA_ERROR_UNSUPPORTED_PTX_VERSION" entries?  From what I've read those come from mis-matched kernel driver and toolkit versions (one is too old for the other).  It's not really a CUDA version thing or a Bifrost thing but more of an installation thing.

**Comment by dentalfloss1** [comment]
Sounds good. Maybe we can just add a footnote that errors can occur from mismatched drivers?

Sent from my iPhone

On Jul 22, 2024, at 1:12 PM, jaycedowell ***@***.***> wrote:

﻿
  [EXTERNAL]

What do you think about dropping the "CUDA_ERROR_UNSUPPORTED_PTX_VERSION" entries? From what I've read those come from mis-matched kernel driver and toolkit versions (one is too old for the other). It's not really a CUDA version thing or a Bifrost thing but more of an installation thing.

**Pull request merged**
