### PR TITLE
Testbench and Tools Modernization

### PR DESCRIPTION
**Pull request by jaycedowell**
Work on modernizing the testbench and tools scripts by converting over to print_function and argparse.  Also, added a simple test suite that uses pylint to give the scripts a basic sanity check during testing.

### CODE REVIEW

**Comment by telegraphic** [comment]
Had a quick (i.e. not comprehensive) look through and think this all looks great. OK to merge IMO

**Comment by jaycedowell** [comment]
test_scripts.py runs a static analysis of the scripts using pylint to try and find obvious errors.  It is not as good as actually running the script with data and comparing the output but I think that it is better than nothing.

**Comment by telegraphic** [comment]
Ah ok, well still LGTM.

**Comment by jaycedowell** [comment]
Let's do this!

**Pull request merged**
